INSERT INTO mp_v2_services (path, upstream_url, name) VALUES ('identity-api-real-rewards', 'http://identity-api-real-rewards.identity-api-real-rewards:3000', 'identity-api-real-rewards');
INSERT INTO mp_v2_scenarios (name, service, request_method, request_path, request_condition, response_code, response_body, response_headers) VALUES ('status_500_error_json', 'identity-api-real-rewards', null, null, null, 500, '{ "status": "error"}', '{"Content-Type":"text/json; charset=UTF-8"}');
INSERT INTO mp_v2_scenarios (name, service, request_method, request_path, request_condition, response_code, response_body, response_headers) VALUES ('status_500_error_html', 'identity-api-real-rewards', null, null, null, 500, '<html><body>Error</body></html>', '{"Content-Type":"text/html; charset=UTF-8"}');
INSERT INTO mp_v2_scenarios (name, service, request_method, request_path, request_condition, response_code, response_body, response_headers) VALUES ('status_400_error_json', 'identity-api-real-rewards', null, null, null, 400, '{ "status": "error"}', '{"Content-Type":"text/json; charset=UTF-8"}');
INSERT INTO mp_v2_scenarios (name, service, request_method, request_path, request_condition, response_code, response_body, response_headers) VALUES ('status_400_error_html', 'identity-api-real-rewards', null, null, null, 400, '<html><body>Error</body></html>', '{"Content-Type":"text/html; charset=UTF-8"}');
INSERT INTO mp_v2_scenarios (name, service, request_method, request_path, request_condition, response_code, response_body, response_headers) VALUES ('status_200_invalid_body', 'identity-api-real-rewards', null, null, null, 200, '<html><body>Invalid Response</body></html>', '{"Content-Type":"text/html; charset=UTF-8"}');

INSERT INTO mp_v2_services (path, upstream_url, name) VALUES ('identity-api-fh-mobile', 'http://identity-api-fh-mobile.identity-api-fh-mobile:3000', 'identity-api-fh-mobile');
INSERT INTO mp_v2_scenarios (name, service, request_method, request_path, request_condition, response_code, response_body, response_headers) VALUES ('status_500_error_json', 'identity-api-fh-mobile', null, null, null, 500, '{ "status": "error"}', '{"Content-Type":"text/json; charset=UTF-8"}');
INSERT INTO mp_v2_scenarios (name, service, request_method, request_path, request_condition, response_code, response_body, response_headers) VALUES ('status_500_error_html', 'identity-api-fh-mobile', null, null, null, 500, '<html><body>Error</body></html>', '{"Content-Type":"text/html; charset=UTF-8"}');
INSERT INTO mp_v2_scenarios (name, service, request_method, request_path, request_condition, response_code, response_body, response_headers) VALUES ('status_400_error_json', 'identity-api-fh-mobile', null, null, null, 400, '{ "status": "error"}', '{"Content-Type":"text/json; charset=UTF-8"}');
INSERT INTO mp_v2_scenarios (name, service, request_method, request_path, request_condition, response_code, response_body, response_headers) VALUES ('status_400_error_html', 'identity-api-fh-mobile', null, null, null, 400, '<html><body>Error</body></html>', '{"Content-Type":"text/html; charset=UTF-8"}');
INSERT INTO mp_v2_scenarios (name, service, request_method, request_path, request_condition, response_code, response_body, response_headers) VALUES ('status_200_invalid_body', 'identity-api-fh-mobile', null, null, null, 200, '<html><body>Invalid Response</body></html>', '{"Content-Type":"text/html; charset=UTF-8"}');

INSERT INTO mp_v2_services (path, upstream_url, name) VALUES ('real-rewards-api', 'http://real-rewards-api-v2.real-rewards-api:3000', 'real-rewards-api');
INSERT INTO mp_v2_scenarios (name, service, request_method, request_path, request_condition, response_code, response_body, response_headers) VALUES ('demo_content', 'real-rewards-api', 'GET', 'content', '$request.body.userId == "4a30d84d-b820-4396-81b3-bc010aa95c01"', 200, 'file:demo-content.json', '{"Content-Type":"text/json; charset=UTF-8"}');
INSERT INTO mp_v2_scenarios (name, service, request_method, request_path, request_condition, response_code, response_body, response_headers) VALUES ('spent-voucher-test-1', 'real-rewards-api', 'GET', 'content', null, 200, 'file:spent-voucher-test-1.json', '{"Content-Type":"text/json; charset=UTF-8"}');
INSERT INTO mp_v2_scenarios (name, service, request_method, request_path, request_condition, response_code, response_body, response_headers) VALUES ('spent-voucher-test-2', 'real-rewards-api', 'GET', 'content', null, 200, 'file:spent-voucher-test-2.json', '{"Content-Type":"text/json; charset=UTF-8"}');
INSERT INTO mp_v2_scenarios (name, service, request_method, request_path, request_condition, response_code, response_body, response_headers) VALUES ('status_500_error_json', 'real-rewards-api', null, null, null, 500, '{ "status": "error"}', '{"Content-Type":"text/json; charset=UTF-8"}');
INSERT INTO mp_v2_scenarios (name, service, request_method, request_path, request_condition, response_code, response_body, response_headers) VALUES ('status_500_error_html', 'real-rewards-api', null, null, null, 500, '<html><body>Error</body></html>', '{"Content-Type":"text/html; charset=UTF-8"}');
INSERT INTO mp_v2_scenarios (name, service, request_method, request_path, request_condition, response_code, response_body, response_headers) VALUES ('status_400_error_json', 'real-rewards-api', null, null, null, 400, '{ "status": "error"}', '{"Content-Type":"text/json; charset=UTF-8"}');
INSERT INTO mp_v2_scenarios (name, service, request_method, request_path, request_condition, response_code, response_body, response_headers) VALUES ('status_400_error_html', 'real-rewards-api', null, null, null, 400, '<html><body>Error</body></html>', '{"Content-Type":"text/html; charset=UTF-8"}');
INSERT INTO mp_v2_scenarios (name, service, request_method, request_path, request_condition, response_code, response_body, response_headers) VALUES ('status_200_invalid_body', 'real-rewards-api', null, null, null, 200, '<html><body>Invalid Response</body></html>', '{"Content-Type":"text/html; charset=UTF-8"}');

INSERT INTO mp_v2_services (path, upstream_url, name) VALUES ('fh-mobile-api', 'http://fh-mobile-api.fh-mobile-api:3000', 'fh-mobile-api');
INSERT INTO mp_v2_scenarios (name, service, request_method, request_path, request_condition, response_code, response_body, response_headers) VALUES ('status_500_error_json', 'fh-mobile-api', null, null, null, 500, '{ "status": "error"}', '{"Content-Type":"text/json; charset=UTF-8"}');
INSERT INTO mp_v2_scenarios (name, service, request_method, request_path, request_condition, response_code, response_body, response_headers) VALUES ('status_500_error_html', 'fh-mobile-api', null, null, null, 500, '<html><body>Error</body></html>', '{"Content-Type":"text/html; charset=UTF-8"}');
INSERT INTO mp_v2_scenarios (name, service, request_method, request_path, request_condition, response_code, response_body, response_headers) VALUES ('status_400_error_json', 'fh-mobile-api', null, null, null, 400, '{ "status": "error"}', '{"Content-Type":"text/json; charset=UTF-8"}');
INSERT INTO mp_v2_scenarios (name, service, request_method, request_path, request_condition, response_code, response_body, response_headers) VALUES ('status_400_error_html', 'fh-mobile-api', null, null, null, 400, '<html><body>Error</body></html>', '{"Content-Type":"text/html; charset=UTF-8"}');
INSERT INTO mp_v2_scenarios (name, service, request_method, request_path, request_condition, response_code, response_body, response_headers) VALUES ('status_200_invalid_body', 'fh-mobile-api', null, null, null, 200, '<html><body>Invalid Response</body></html>', '{"Content-Type":"text/html; charset=UTF-8"}');

INSERT INTO mp_v2_services (path, upstream_url, name) VALUES ('supervalu-loyalty-web-api', 'http://supervalu-loyalty-web-api-v2.supervalu-loyalty-web-api:3000', 'supervalu-loyalty-web-api');
INSERT INTO mp_v2_scenarios (name, service, request_method, request_path, request_condition, response_code, response_body, response_headers) VALUES ('modify_code', 'supervalu-loyalty-web-api', 'GET', 'content', null, 418, null, null);
INSERT INTO mp_v2_scenarios (name, service, request_method, request_path, request_condition, response_code, response_body, response_headers) VALUES ('modify_headers', 'supervalu-loyalty-web-api', 'GET', 'content', null, null, null, '{"the-answer-to-life-the-universe-and-everything":"42"}');
INSERT INTO mp_v2_scenarios (name, service, request_method, request_path, request_condition, response_code, response_body, response_headers) VALUES ('modify_body', 'supervalu-loyalty-web-api', 'GET', 'content', null, 200, 'Yippie-ki-yay', null);
INSERT INTO mp_v2_scenarios (name, service, request_method, request_path, request_condition, response_code, response_body, response_headers) VALUES ('global', 'supervalu-loyalty-web-api', null, null, null, 500, '{"status": "intercepted"}', '{"Content-Type":"text/json; charset=UTF-8"}');
INSERT INTO mp_v2_scenarios (name, service, request_method, request_path, request_condition, response_code, response_body, response_headers) VALUES ('with_condition', 'supervalu-loyalty-web-api', 'POST', 'cards', '$request.body.cardNumber == "123456789"', 200, '{"status": "intercepted"}', '{"Content-Type":"text/json; charset=UTF-8"}');
INSERT INTO mp_v2_scenarios (name, service, request_method, request_path, request_condition, response_code, response_body, response_headers) VALUES ('liquidjs', 'supervalu-loyalty-web-api', 'GET', 'content', null, 200, '<% TEMPLATE: LiquidJS %>{% assign seconds = 5 | times: 24 | times: 60 | times: 60 %}{"validFrom": "{{ 'now' | date: "%s" | plus: seconds | date: "%Y-%m-%d" }}"}', '{"Content-Type":"text/json; charset=UTF-8"}');
